config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios 
  root 'bienvenida#indice'

   resources :votes

  resources :archivos do
    member do
      get :vote_for, :vote_against
    end
  end

  resources :profesors

  resources :cursos 

  resources :consulta

  resources :comentarios

  resources :usuarios

get 'cursos/:id/consultas' => 'cursos#consultas', as: :consultas_curso

end

app/models/profesor.rb
class Profesor < ActiveRecord::Base
	has_and_belongs_to_many :cursos
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:create]
  # GET /profesors
  # GET /profesors.json
  def index
    if params[:curso]
      @curso = Curso.where(id: params[:curso]).first
      @profesors = @curso.profesors.paginate(:per_page => 5, :page => params[:page])

    else
      @profesors = Profesor.all.paginate(:per_page => 5, :page => params[:page])

    end
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new
    @profesor.nombre = profesor_params[:nombre]
    @profesor.descripcion = profesor_params[:descripcion]
    
    if profesor_params[:curso_id] != ""

          Curso.find(profesor_params[:curso_id]).profesors << @profesor
          respond_to do |format|
            if @profesor.save
              format.html { redirect_to profesor_path(@profesor,:curso =>Curso.find(profesor_params[:curso_id]).id), notice: 'Profesor fue creado con exito.' }
              format.json { render :show, status: :created, location: @profesor }
            else
              format.html { render :new }
              format.json { render json: @profesor.errors, status: :unprocessable_entity }
            end
          end
    else
            respond_to do |format|
            if @profesor.save
              format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
              format.json { render :show, status: :created, location: @profesor }
            else
              format.html { render :new }
              format.json { render json: @profesor.errors, status: :unprocessable_entity }
            end
          end
    end

  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
       @profesor.nombre = profesor_params[:nombre]
       @profesor.descripcion = profesor_params[:descripcion]

      if @profesor.save
        format.html { redirect_to profesor_path(@profesor,:curso => profesor_params[:curso_id]), notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
     if params[:curso]
      respond_to do |format|
        format.html { redirect_to profesors_path(:curso => params[:curso]), notice: 'Profesor was successfully destroyed.' }
       format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to profesors_url, notice: 'Profesor was successfully destroyed.' }
       format.json { head :no_content }
     end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:nombre, :descripcion, :curso_id)
    end
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/views/profesors/_form.html.erb
<%= bootstrap_form_for(@profesor) do |f| %>
  <% if @profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% @profesor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.text_area :descripcion %>
    <%= f.hidden_field :curso_id, :value => params[:curso]%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profesors/edit.html.erb
<h1>Editar profesor</h1>

<%= render 'form' %>

<%= link_to "Atras", profesors_path( :curso => params[:curso]), :class => "btn btn-default" %>

app/views/profesors/index.html.erb
<% if usuario_signed_in? and current_usuario.isAdmin %>
  <h1>Mantener Profesor</h1>
<% else %>
  <h1> Profesores </h1>

<% end %>
<% if usuario_signed_in? %>
<div class = "media">
   <div class =  "media-body">
    <table class = "table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesors.each do |profesor| %>
      <tr>
            <td><%= profesor.nombre %></td>
            <td><%= profesor.descripcion %></td>
            <% if usuario_signed_in? and current_usuario.isAdmin %>
              <td><%= link_to 'Editar', edit_profesor_path(profesor, :curso => params[:curso]), class: 'btn btn-mini btn-success' %></td>
              <td><%= link_to 'Eliminar', profesor_path(profesor,:curso => params[:curso]), class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Esta seguro?' } %></td>
            <% end %>  
          </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

<br>
  <% if usuario_signed_in? and current_usuario.isAdmin %>
    <%if params[:curso]!=""%>
     <%= link_to 'Nuevo Profesor', new_profesor_path( :curso => params[:curso]), :class => "btn btn-default" %>
    <%else%>
      <%= link_to 'Nuevo Profesor', new_profesor_path, :class => "btn btn-default" %>
    <%end%>
  <%end%>
 <%= link_to "Atras", @curso, :class => "btn btn-success  " %>
<% end %>

app/views/profesors/new.html.erb
<h1>Nuevo profesor</h1>

<%= render 'form' %>

<%= link_to 'Atras', profesors_path(:curso => params[:curso]), :class => "btn btn-default" %>

app/views/profesors/show.html.erb
<div class= "jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @profesor.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @profesor.descripcion %>
</p>

<%= link_to "Editar", edit_profesor_path(@profesor,:curso => params[:curso]), :class => "btn btn-default" %>
<%= link_to "Atras", profesors_path( :curso => params[:curso]), :class => "btn btn-default" %>
</div>