config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios 
  root 'bienvenida#indice'

   resources :votes

  resources :archivos do
    member do
      get :vote_for, :vote_against
    end
  end

  resources :profesors

  resources :cursos 

  resources :consulta

  resources :comentarios

  resources :usuarios

get 'cursos/:id/consultas' => 'cursos#consultas', as: :consultas_curso

end

app/models/curso.rb
class Curso < ActiveRecord::Base
	has_many :consulta
	has_many :archivos
	has_and_belongs_to_many :profesors
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :consultas , :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

 # GET /cursos/1/consulta
  def consultas
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nombre, :descripcion)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= bootstrap_form_for(@curso) do |f| %>
  <% if @curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% @curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cursos/consultas.html.erb
<tbody>

    <% @curso.consulta.each do |consultum| %>

    
      <div class= jumbotron>
      
      <h2>Consulta: <center><%= consultum.descripcion.html_safe %></center></h2>
      <hr class="featurette-divider">
      <hr class="featurette-divider">

      <% if consultum.related_consulta.count >0 %>
        
        <h2>Respuestas:</h2>
        

        <h2><% consultum.related_consulta.each do |consultu| %></h2>
        <hr class="featurette-divider">

        <%= consultu.descripcion.html_safe %>
          
        <% end %>   

      <%end%>
      <%= link_to 'Responder', new_consultum_path( :consultum_id => consultum.id, :curso => params[:curso]  ), class: 'btn btn-mini btn-warning' %>
      
      </div>
      
    <% end %>
    


<%= link_to "Atras", @curso, :class => "btn btn-success" %>
<%= link_to 'Nueva Consulta', new_consultum_path( :curso => @curso.id) , class: 'btn btn-success'%>

app/views/cursos/edit.html.erb
<h1>Editar curso</h1>

<%= render 'form' %>


<%= link_to "Ver",  @curso, :class => "btn btn-default" %>
<%= link_to "Atras", cursos_path, :class => "btn btn-default" %>

app/views/cursos/index.html.erb
<h1>Manter cursos</h1>

<div class = "media">
   <div class =  "media-body">
    <table class = "table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
            <td><%= curso.nombre %></td>
            <td><%= curso.descripcion.html_safe %></td>
            <td><%= link_to 'Editar', edit_curso_path(curso), class: 'btn btn-mini btn-success' %></td>
            <td><%= link_to 'Eliminar', curso, class: 'btn btn-mini btn-danger', method: :delete, data: { confirm: 'Esta seguro?' } %></td>
          </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>


<div>
  
  <%= link_to 'Nuevo curso', new_curso_path, class: 'btn btn-default' %>

  

</div>

app/views/cursos/new.html.erb
<h1>Nuevo curso</h1>

<%= render 'form' %>

<%= link_to 'Atras', cursos_path, :class => "btn btn-default" %>

app/views/cursos/show.html.erb
<div class="jumbotron">

  <center>

<p id="notice"><%= notice %></p>

<% if usuario_signed_in? %>
  <h2>
  <strong>Nombre:</strong>
  <%= @curso.nombre %>
  </h2>


<p>

  <strong>Descripcion:</strong>
  <%= @curso.descripcion %>
</p>

  </center>

</div>




<div class="jumbotron">

  <center>

<%= link_to "Archivos"+"(#{@curso.archivos.count})", archivos_path( :curso => @curso.id) , :class =>'btn btn-success' %>

<%= link_to "Preguntas y Respuestas"+"(#{@curso.consulta.count})", consultas_curso_path( :curso => @curso.id), class: 'btn btn-success' %>



<%= link_to "Profesores"+"(#{@curso.profesors.count})", profesors_path( :curso => @curso.id) , :class => 'btn btn-success' %>

</center>

</div>

<div class="jumbotron">


<% consultas = @curso.consulta.paginate(:page => params[:page], :per_page => 5)%>
<h2>Preguntas Recientes</h2>
<div class = "media">
   <div class =  "media-body">


   


    <table class = "table table-hover">
  <thead>
    <tr>
      <th>Pregunta</th>
      <th>Respuestas</th>
      <th colspan="3"></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% consultas.each do |consultum| %>
      <tr>
            <td><%= consultum.descripcion.html_safe %></td>            
            <td><%= consultum.related_consulta.count %></td>
           
           
      </tr>
      
    <% end %>
  </tbody>
</table>
<%= will_paginate consultas %>
  </div>
</div>
<br>
<!-- asdfasdfasdfdsaf -->
<%= link_to 'Nueva Consulta', new_consultum_path( :curso => params[:curso]) , class: 'btn btn-success'%>


      <% else %>
       
        Debe iniciar Sesion
      <% end %>

</div>