config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios 
  root 'bienvenida#indice'

   resources :votes

  resources :archivos do
    member do
      get :vote_for, :vote_against
    end
  end

  resources :profesors

  resources :cursos 

  resources :consulta

  resources :comentarios

  resources :usuarios

get 'cursos/:id/consultas' => 'cursos#consultas', as: :consultas_curso

end

app/models/archivo.rb
class Archivo < ActiveRecord::Base
	acts_as_voteable
	belongs_to :Curso
	def self.search(search)
	    if search
	      where('descripcion LIKE ?', "%#{search}%")
	    else
	      all
	    end
  end

end

app/controllers/archivos_controller.rb
class ArchivosController < ApplicationController
  before_action :set_archivo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:create]


  def vote_for
      begin
        @archivo = Archivo.find(params[:id])
        current_usuario.vote_for(@archivo)
        redirect_to archivos_path(:page => params[:page], :curso => params[:curso])
      rescue ActiveRecord::RecordInvalid
        redirect_to archivos_path(:page => params[:page], :curso => params[:curso])
      end
    end



  # GET /archivos
  # GET /archivos.json
  def index
    
    if params[:curso]
      @curso = Curso.where(id: params[:curso]).first
      @archivos = @curso.archivos.search(params[:search]).paginate(:per_page => 5, :page => params[:page])

    else
      @archivos = Archivo.all.search(params[:search]).paginate(:per_page => 5, :page => params[:page])

    end
    
  end

  # GET /archivos/1
  # GET /archivos/1.json
  def show

  end

  # GET /archivos/new
  def new
    @archivo = Archivo.new
  end

  # GET /archivos/1/edit
  def edit
  end

  # POST /archivos
  # POST /archivos.json
  def create
    @archivo = Archivo.new(archivo_params)

      respond_to do |format|
        if @archivo.save
          format.html { redirect_to @archivo, notice: 'Archivo was successfully created.' }
          format.json { render :show, status: :created, location: @archivo }
        else
          format.html { render :new }
          format.json { render json: @archivo.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /archivos/1
  # PATCH/PUT /archivos/1.json
  def update
    respond_to do |format|
      if @archivo.update(archivo_params)
        format.html { redirect_to @archivo, notice: 'Archivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @archivo }
      else
        format.html { render :edit }
        format.json { render json: @archivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archivos/1
  # DELETE /archivos/1.json
  def destroy
    @archivo.destroy
    respond_to do |format|
      format.html { redirect_to archivos_url, notice: 'Archivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archivo
      @archivo = Archivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archivo_params
      params.require(:archivo).permit(:url, :curso_id,:descripcion, :puntuacion)
    end
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/views/archivos/_form.html.erb
<%= bootstrap_form_for(@archivo) do |f| %>


  <% if @archivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@archivo.errors.count, "error") %> prohibited this archivo from being saved:</h2>

      <ul>
      <% @archivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.text_area :descripcion %>
    <%= f.hidden_field :curso_id, :value => params[:curso]%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/archivos/edit.html.erb
<h1>Mantener archivo</h1>


<%= render 'form' %>


<%= link_to "Ver", @archivo, :class => "btn btn-default" %>
<%= link_to "Atras", archivos_path(:curso => params[:curso]), :class => "btn btn-default" %>

app/views/archivos/index.html.erb
<% if usuario_signed_in? and current_usuario.isAdmin %>
  <h1>Mantener archivos</h1>
<% else %>
  <h1> Archivos </h1>
<% end %>  

<% if usuario_signed_in? %>
<div class = "media">
   <div class =  "media-body">
    <table class = "table table-hover">
  <thead>
    <tr>
      <th>Url</th>
      <th>Descripcion</th>
      
      <th>Cantidad de Votos</th>
      
    </tr>
  </thead>

  <tbody>
    <% @archivos.each do |archivo| %>
     <tr>

            <td><%= link_to archivo.url, "http://"+archivo.url %></td> 

            <td><%= archivo.descripcion %></td>




            <% if usuario_signed_in? and current_usuario.isAdmin %>

             
              <td><%= link_to 'Editar', edit_archivo_path(archivo), class: 'btn btn-mini btn-success' %></td>
              <td><%= link_to 'Eliminar', archivo, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Esta seguro?' } %></td>
              <td class="votes"><%= pluralize( archivo.votes.count, 'Vote') %></td>

              <td><%= link_to 'Votar', vote_for_archivo_path(archivo, :page => params[:page], :curso => params[:curso]), class: 'btn btn-mini btn-info', :remote => false %></td>
               <% else %>
                <% if  usuario_signed_in? %>
                      <td class="votes"><%= pluralize( archivo.votes.count, 'Vote') %></td>

                      <td><%= link_to 'Votar', vote_for_archivo_path(archivo, :page => params[:page], :curso => params[:curso]), class: 'btn btn-mini btn-info', :remote => false %></td>
                       
                <% end %> 
            <% end %>  
          </tr>
    <% end %>
  </tbody>
</table>


<div>
  <%= link_to "Atras", @curso, :class => "btn btn-success" %>


<%if params[:curso]!=""%>
  <%= link_to 'Nuevo Archivo', new_archivo_path( :curso => params[:curso]), class: 'btn btn-success' %>
<%else%>
  <%= link_to 'Nuevo Archivo', new_archivo_path, class: 'btn btn-success' %>
<%end%>



</div>



<%= will_paginate @archivos, renderer: BootstrapPagination::Rails %>  


  
  </div>
</div>

<br>

<% end %>

app/views/archivos/new.html.erb
<h1>Nuevo Archivo</h1>


<%= render 'form' %>



<!--
<%= link_to 'Back', archivos_path %>
-->

app/views/archivos/show.html.erb
<!--
<div class= "jumbotron">
<p id="notice"><%= notice %></p>





<p>
  <strong>Url:</strong>
  <%= @archivo.url %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @archivo.descripcion %>
</p>

<p>
  <strong>Puntuacion:</strong>
  <%= @archivo.puntuacion %>
</p>


<%= link_to "Editar", edit_archivo_path(@archivo), :class => "btn btn-default" %>



<%= link_to "Atras", archivos_path(:curso => params[:curso]), :class => "btn btn-default" %>

-->

<div class= "jumbotron">


<h2>Gracias por participar ;)</h2>

<%= link_to "Volver",  root_path , :class => "btn btn-default" %>


</div>