config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios 
  root 'bienvenida#indice'

   resources :votes

  resources :archivos do
    member do
      get :vote_for, :vote_against
    end
  end

  resources :profesors

  resources :cursos 

  resources :consulta

  resources :comentarios

  resources :usuarios

get 'cursos/:id/consultas' => 'cursos#consultas', as: :consultas_curso

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Educandus</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "defaults", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>


<body>

    <div class="navbar  navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
          </button>

          <a class="navbar-brand">EDUCANDUS</a>
        </div>
        <div class="navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <% if usuario_signed_in? and current_usuario.isAdmin %>
             <li><%= link_to "Inicio", root_path %></li>
             <li><%= link_to "Preguntas", consulta_path %></li>
             <li><%= link_to "Cursos", cursos_path %></li>
             <li><%= link_to "Profesores", profesors_path %></li>
             <li><%= link_to "Archivos", archivos_path %></li>
             <li><%= link_to "Usuarios", usuarios_path %></li>
            <% else %>
             <li><%= link_to "Inicio", root_path %></li>
             
            <% end %>
          </ul>


          <ul class="navbar-collapse collapse nav navbar-nav navbar-right">
            <% if usuario_signed_in? %>
                <p1>Sesion: <strong><%= current_usuario.email %></strong>.</p1>
                <li><%= link_to 'Editar Perfil', edit_usuario_registration_path, :class => 'btn btn-success' %></li>
                <li><%= link_to "Cerrar sesion", destroy_usuario_session_path %></li>
            <% else %>
              <li><%= link_to "Registrarse", new_usuario_registration_path, :class => 'btn-success'%> </li>
              <li><%= link_to "Iniciar sesion", new_usuario_session_path, :class => 'btn-warning'  %></li>
            <% end %>            
            
          </ul>
        </div>
      </div>
    </div>
    <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>

    <div class="container-fluid">
      
        <div class="navbar sidebar col-sm-1 col-md-2 ">
          <h3>Cursos</h3>

          <% Curso.all.each do |curso| %>
          <ul class="nav  nav-stacked">  
             <% if !usuario_signed_in?   %>
                  <hr class="featurette-divider">
                  <li><%= link_to curso.nombre, new_usuario_session_path, :class => 'btn-block'  %></li>
             <% else %>         
            <li><%= link_to curso.nombre, curso_path(curso,:curso => curso.id), :class => 'btn-block' %> </li>
            <hr class="featurette-divider"> 
            <% end %>
            <% end %>
          </ul>

        


        </div>

        <div class="col-sm-6 col-md-9 main">
          <div>
            <%= yield %>  
          </div>                  
        </div>

      
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>

    <div class="footer">
        <p>&copy; Tecnologias Web 2014</p>
      </div>

  </body>



    
          
    </div>


  </div>
  </div>
</div>


</html>